---
resources:
    - name: "mafiasi-dashboard-git"
      type: "git"
      source:
          uri: "https://github.com/fsinfuhh/mafiasi.git"
          branch: "((branch))"
    - name: "mafiasi-dashboard-image"
      type: "registry-image"
      source:
          repository: "registry.mafiasi.de/dashboard"
          tag: "((branch))-latest"
          username: "((registry-username))"
          password: "((registry-password))"

jobs:
    - name: "update-oci-image"
      plan:
          - get: "mafiasi-dashboard-git"
            trigger: true
          - task: "build"
            privileged: true
            config:
                platform: "linux"
                image_resource:
                    type: "registry-image"
                    source:
                        repository: "docker.io/vito/oci-build-task"
                params:
                    CONTEXT: "mafiasi-dashboard-git"
                inputs:
                    - name: "mafiasi-dashboard-git"
                outputs:
                    - name: "image"
                caches:
                    - path: "cache"
                run:
                    path: "build"
          - put: "mafiasi-dashboard-image"
            params:
                image: "image/image.tar"

