# build using: docker build -f Dockerfile.pre-commit -t mafiasi-pre-commit .
# run using: docker run --rm -it -v "$PWD:/app/src" mafiasi-pre-commit

FROM docker.io/debian:bookworm-slim

# Install base system dependencies
RUN apt update
# https://stackoverflow.com/questions/58160597/docker-fails-with-sub-process-usr-bin-dpkg-returned-an-error-code-1
RUN mkdir -p /usr/share/man/man1 /app/config
ENV DEBIAN_FRONTEND=noninteractive
RUN apt upgrade -y &&\
    apt install -y --no-install-recommends uwsgi uwsgi-plugin-python3 python3 python3-setuptools python3-pip gcc gettext \
    libldap-common libldap2-dev libsasl2-2 libsasl2-dev libgpgme11 libgpgme-dev python3-dev libgraphviz-dev graphviz libmagic-dev libjpeg-dev libjs-mathjax \
    make nginx supervisor pipenv python-is-python3 git

# add Pipfile seperate from other sources to take advantage of build caching
ADD Pipfile /app/src/Pipfile
ADD Pipfile.lock /app/src/Pipfile.lock
WORKDIR /app/src
# delete file that marks root python package path as externally managed
RUN rm /usr/lib/python3.11/EXTERNALLY-MANAGED
RUN pipenv lock --clear
RUN pipenv install --system --deploy --ignore-pipfile --verbose
RUN pipenv install --dev --deploy --ignore-pipfile
RUN pip3 install sentry-sdk
RUN pip3 install --no-cache-dir pre-commit
RUN git config --global --add safe.directory /app/src

# add remaining sources
ADD . /app/src

# Pre-create hook environments during the image build.
RUN pre-commit install-hooks

ENTRYPOINT ["pre-commit"]
CMD ["run", "--show-diff-on-failure", "--color=always", "--all-files"]
