# Generated by Django 3.2 on 2022-03-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gprot", "0004_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="url",
            field=models.CharField(max_length=500),
        ),
    ]
