# Generated by Django 4.1 on 2023-07-27 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gprot", "0005_alter_favorite_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedGprots",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pdf_hash", models.CharField(max_length=64)),
                ("gprot_title", models.CharField(max_length=100)),
                (
                    "blocked_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
