# Generated by Django 3.1.7 on 2021-04-13 15:51

from django.db import migrations, models

import mafiasi.base.validation


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_auto_20210325_1312"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mafiasi",
            name="account",
            field=models.CharField(max_length=64, validators=[mafiasi.base.validation.validate_ascii]),
        ),
    ]
