# Generated by Django 3.2 on 2021-08-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_auto_20210413_1751"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswdEntry",
        ),
    ]
