# Generated by Django 3.2 on 2021-08-30 16:39

from django.db import migrations


def create_employee_yeargroup(apps, schema_editor):
    Yeargroup = apps.get_model("base", "Yeargroup")
    db_alias = schema_editor.connection.alias
    if not Yeargroup.objects.using(db_alias).filter(slug='employee').exists():
        yeargroup = Yeargroup.objects.using(db_alias).create(slug='employee', name='Employee')
        if apps.is_installed('jabber'):
            from mafiasi.jabber import models
            models.create_yeargroup(yeargroup, created=True)


class Migration(migrations.Migration):
    """This migration is used to create an "employee" yeargroup which is required for the REGISTRATION_LDAP code."""

    dependencies = [
        ('base', '0012_delete_passwdentry'),
        ('jabber', '0004_alter_created_at'),
    ]

    operations = [
        migrations.RunPython(create_employee_yeargroup)
    ]
