# Generated by Django 3.2 on 2021-09-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_delete_passwdentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yeargroup',
            name='gid',
        ),
    ]
