# Generated by Django 5.1.6 on 2026-10-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_remove_yeargroup_gid"),
    ]

    operations = [
        migrations.AddField(
            model_name="mafiasi",
            name="preferred_name",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
