---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "mafiasi-dashboard"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "mafiasi-dashboard"

  template:
    metadata:
      labels:
        app: "mafiasi-dashboard"
    spec:
      imagePullSecrets:
        - name: "registry-credentials"
      nodeSelector:
        kubernetes.io/hostname: "fs6"
      securityContext:
        supplementalGroups:
          - 33  # www-data

      volumes:
        - name: "config"
          configMap:
            name: "mafiasi-dashboard"
        - name: "media"
          hostPath:
            path: "/srv/dashboard/storage/media"
        - name: "gnupg"
          hostPath:
            path: "/srv/dashboard/storage/.gnupg"

      containers:
        # dashboard backend
        - image: "registry.mafiasi.de/mafiasi-dashboard:master-latest"
          name: "main"
          ports:
            - name: "http"
              containerPort: 8000
          volumeMounts:
            - name: "config"
              mountPath: "/app/config"
              readOnly: true
            - name: "media"
              mountPath: "/app/media"
            - name: "gnupg"
              mountPath: "/app/.gnupg"
