---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "mafiasi-dashboard"
spec:
  type: "ClusterIP"
  selector:
    app: "mafiasi-dashboard"
  ports:
    - name: "http"
      port: 80
      targetPort: "http"
    - name: "hkp"
      port: 11371
      targetPort: "hkp"
