# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jabber', '0002_auto_20150515_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='SrInactiveUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.TextField()),
                ('grp', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sr_inactive_user',
            },
        ),
        migrations.AlterField(
            model_name='jabberuser',
            name='password',
            field=models.TextField(default=b'NO_PASSWORDS_IN_DB_ZYYJN53N3M5QMHNQKLOAQD7E'),
        ),
        migrations.AlterUniqueTogether(
            name='srinactiveuser',
            unique_together=set([('jid', 'grp')]),
        ),
    ]
