# Generated by Django 3.2 on 2021-09-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jabber', '0003_auto_20161011_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sruser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='srgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
