name: test
on:
  workflow_dispatch: {}
  workflow_call: {}
  push: {}

jobs:

  check-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pipenv
      - name: install dependencies
        run: pip install pre-commit pipenv
      - name: install project dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends libgpgme-dev libsasl2-dev libldap2-dev libmagic-dev libjpeg-dev libgraphviz-dev gettext
          pipenv sync --dev
      - name: execute pre-commit check
        run: pre-commit run --show-diff-on-failure --color=always --all-files

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: "postgres:15"
        env:
          POSTGRES_DB: mafiasi-dashboard
          POSTGRES_USER: mafiasi-dashboard
          POSTGRES_PASSWORD: mafiasi-dashboard
        ports:
          - 5432
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pipenv
      - name: install pipenv
        run: pip install pipenv
      - name: install project dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends libgpgme-dev libsasl2-dev libldap2-dev libmagic-dev libjpeg-dev libgraphviz-dev gettext
          pipenv sync --dev
      - name: run tests
        run: pipenv run pytest

  compile_messages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pipenv
      - name: install pipenv
        run: pip install pipenv
      - name: install project dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends libgpgme-dev libsasl2-dev libldap2-dev libmagic-dev libjpeg-dev libgraphviz-dev gettext
          pipenv sync --dev
      - name: compile i18n messages
        env:
          MAFIASI_ENV_FILE: .env.test
        run: pipenv run ./manage.py compilemessages
